apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoexpress_service_name }}    
spec:
  selector:
    app: {{ .Values.mongo_express_label_name }}
  type: {{ .Values.service_type }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.mongoexpress_service_port }}
      targetPort: {{ .Values.mongoexpress_target_port }}
      nodePort: {{ .Values.nodeport }}