apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv_name }}
  labels:
    name: {{ .Values.pv_label_name }}
spec:
  storageClassName: {{ .Values.storage_class }}
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - {{ .Values.access_mode }}
  nfs:
    server: {{ .Values.nfs_server_ip }}
    path: {{ .Values.path }} 