apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc_name }}
spec:
  storageClassName: {{ .Values.storage_class }}
  accessModes:
    - {{ .Values.access_mode }} 
  resources:
    requests:
      storage: {{.Values.pvc_storage}} 